name: Process Chunk

on:
  workflow_call:
    inputs:
      chunk-data:
        required: true
        type: string
      max-parallel:
        required: false
        type: number
        default: 2    
    secrets:
      CMR_USER:
        required: true
      CMR_PASS:
        required: true
permissions:
  actions: read   # needed to query jobs API
  contents: read  # optional, if accessing repo files
jobs:
  process:
    runs-on: ubuntu-latest
    env:
      CMR_USER: ${{ secrets.CMR_USER }}
      CMR_PASS: ${{ secrets.CMR_PASS }}
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: false
      matrix: ${{ fromJson(inputs.chunk-data) }}
    steps:

      - name: Echo current matrix job URL
        run: |
          echo "Fetching URL for current matrix job..."

          # Get all jobs in this workflow run
          RESPONSE=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs")

          # Get the job ID that matches this matrix job
          JOB_ID=$(echo "$RESPONSE" | jq -r --arg JOB "$GITHUB_JOB" '.jobs[] | select(.name | startswith($JOB)) | .id')

          # Construct the job URL
          JOB_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs/$JOB_ID"

          # Echo it
          echo "Matrix job URL: $JOB_URL"


      - name: Get job-specific URL
        run: |
          echo "Fetching job URL for ${{ github.job }}..."
          JOB_URL=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
            | jq -r --arg JOB "${{ github.job }}" '.jobs[] | select(.name | startswith($JOB)) | .html_url')
          echo "Job URL: $JOB_URL"


      - name: Print env and file
        run: echo "Env=${{ matrix.env }} File=${{ matrix.file }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.3

      - name: Poetry Install
        run: poetry install

      - name: Run Regression
        working-directory: tests
        run: |
          poetry run pytest verify_collection.py --env ${{ matrix.env }} --concept_id ${{ matrix.file }}



